spring:
  application:
    name: new-layui
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://120.24.195.30:3306/cdb?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: Rshz123$%^
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss

logging.level.org.springframework.boot.autoconfigure: ERROR
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/templates/

server:
  port: 8110
debug: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/